import React from "react";
import {
  SiNextdotjs,
  SiTypescript,
  SiTailwindcss,
  SiWordpress,
  SiRadixui,
  SiShadcnui,
  SiSocketdotio,
  SiFirebase,
  SiPostgresql,
  SiPrisma,
  SiMariadb,
  SiPhp,
  SiElementor,
  SiVercel,
  SiReact,
  SiVite,
  SiZod,
  SiReacthookform,
  SiFramer,
  SiDaisyui,
  SiSwiper,
  SiHeadlessui,
  SiChartdotjs,
  SiAstra,
  SiUikit,
  SiJsonwebtokens,
  SiMaterialdesign,
} from "react-icons/si";
import { FaWpforms } from "react-icons/fa";

export const techStackIcons: Record<string, React.ReactNode> = {
  NextJS: <SiNextdotjs className="text-white" />,
  TypeScript: <SiTypescript className="text-[#3178C6]" />,
  TailwindCSS: <SiTailwindcss className="text-[#06B6D4]" />,
  WordPress: <SiWordpress className="text-white" />,
  RadixUI: <SiRadixui className="text-white" />,
  ShadcnUI: <SiShadcnui className="text-white" />,
  SocketIO: <SiSocketdotio className="text-white" />,
  Firebase: <SiFirebase className="text-yellow-500" />,
  PostgreSQL: <SiPostgresql className="text-blue-500" />,
  Prisma: <SiPrisma className="text-green-500" />,
  MariaDB: <SiMariadb className="text-orange-500" />,
  PHP: <SiPhp className="text-purple-500" />,
  Elementor: <SiElementor className="text-pink-300" />,
  Vercel: <SiVercel className="text-white" />,
  React: <SiReact className="text-blue-500" />,
  Vite: <SiVite className="text-purple-700" />,
  Zod: <SiZod className="text-blue-400" />,
  ReactHookForm: <SiReacthookform className="text-pink-500" />,
  FramerMotion: <SiFramer className="text-yellow-500" />,
  DaisyUI: <SiDaisyui className="text-yellow-500" />,
  Swiper: <SiSwiper className="text-blue-700" />,
  HeadlessUI: <SiHeadlessui className="text-cyan-500" />,
  ChartJS: <SiChartdotjs className="text-pink-400" />,
  WpForms: <FaWpforms className="text-orange-800" />,
  Astra: <SiAstra className="text-purple-600" />,
  UIKit: <SiUikit className="text-cyan-500" />,
  JWT: <SiJsonwebtokens className="text-yellow-300" />,
  MaterialUI: <SiMaterialdesign className="text-white" />,
};

export const getTechStackIcon = (techName: string) => {
  return techStackIcons[techName] || null;
};
